export const people_data = [
  {
    id: 1,
    first: "Aidan",
    last: "Wang",
    picture: "https://randomuser.me/api/portraits/med/men/93.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 2,
    first: "Anna",
    last: "Horten",
    picture: "https://randomuser.me/api/portraits/med/women/48.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 3,
    first: "Max",
    last: "Arnold",
    picture: "https://randomuser.me/api/portraits/med/men/27.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 4,
    first: "kaison",
    last: "kaison",
    picture: "https://randomuser.me/api/portraits/med/men/34.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 5,
    first: "Emilia",
    last: "Gonz",
    picture: "https://randomuser.me/api/portraits/med/women/90.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 6,
    first: "Alicia",
    last: "Ma",
    picture: "https://randomuser.me/api/portraits/med/women/91.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 7,
    first: "Karl",
    last: "Mon",
    picture: "https://randomuser.me/api/portraits/med/women/64.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 8,
    first: "Rein",
    last: "Barz",
    picture: "https://randomuser.me/api/portraits/med/women/95.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 9,
    first: "Felix",
    last: "Dougs",
    picture: "https://randomuser.me/api/portraits/med/men/53.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 10,
    first: "Claire",
    last: "Rob",
    picture: "https://randomuser.me/api/portraits/med/women/75.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 11,
    first: "Urkel",
    last: "Mona",
    picture: "https://randomuser.me/api/portraits/med/men/80.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 12,
    first: "Tiemo",
    last: "Monsr",
    picture: "https://randomuser.me/api/portraits/med/men/16.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 13,
    first: "Dorian",
    last: "Carr",
    picture: "https://randomuser.me/api/portraits/med/men/77.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 14,
    first: "Ross",
    last: "Geller",
    picture: "https://randomuser.me/api/portraits/med/women/59.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 15,
    first: "Lias",
    last: "Korsvik",
    picture: "https://randomuser.me/api/portraits/med/men/69.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 16,
    first: "Flor",
    last: "Cooper",
    picture: "https://randomuser.me/api/portraits/med/women/19.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 17,
    first: "Donald",
    last: "Ham",
    picture: "https://randomuser.me/api/portraits/med/men/34.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 18,
    first: "Mich",
    last: "Nichol",
    picture: "https://randomuser.me/api/portraits/med/men/76.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 19,
    first: "Emile",
    last: "Miller",
    picture: "https://randomuser.me/api/portraits/med/men/24.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
  {
    id: 20,
    first: "Mar",
    last: "Stuijt",
    picture: "https://randomuser.me/api/portraits/med/women/31.jpg",
    accessPermisson: "No access",
    isSelected: "Select",
  },
];
